# Generated by Django 3.2.2 on 2021-05-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='genderSelection',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='F', max_length=1),
        ),
    ]
